apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- openshift-gitops-gstnonprod.yaml
- resourcequota-manager-clusterrole.yaml
- resourcequota-manager-clusterrolebinding.yaml
