kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: quay-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-3.6'
  - target:
     group: operators.coreos.com
     version: v1alpha1
     kind: Subscription
     name: quay-operator
     namespace: openshift-operators
    patch: |-
      - op: replace
        path: /spec/source
        value: 'redhat-operators'
